### ISSUE TITLE
When a comic is imported with a trailing space in the series name of the comic info file, filtering doesn't work

### ISSUE THREAD

**Issue by RogueBurger** [maforget/ComicRackCE#103]
**Describe the bug**
If a comic has a ComicInfo.xml file with a trailing space in the Series field (e.g. `<Series>Foo Bar </Series>`), the comic does not filter correctly in the ComicRack UI after import.

**Exact Steps to Reproduce**
1. Import a comic with a trailing space in the Series field of the ComicInfo.xml file. For example:
```
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Series>Space Ghost </Series>
    <Issue>4</Issue>
    <Month>8</Month>
    <Year>2024</Year>
</ComicInfo>
```
2. Create a list and add just that comic to it (not necessary to reproduce the bug, just makes it easier to notice)
3. Set one of the top level filters to series, and select the single available series to filter on
4. You should see a completely empty results screen.

**Screenshots**
![Screenshot 2024-08-19 114054](https://github.com/user-attachments/assets/0cbaeaa2-96a7-4de2-a29a-7859b2294fbc)
![Screenshot 2024-08-19 114114](https://github.com/user-attachments/assets/8edf5f40-6680-4167-9914-85083f9763d3)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 67119ff

**Additional context**
Editing the Series name to remove the trailing space, either in the ComicInfo file itself or via ComicRack does fix the issue.

**Comment by RogueBurger** [comment]
I noticed that if you go to edit the Series name in ComicRack, and you put a trailing space in there, the system automatically trims it when you save. So because CR already doesn't let you put trailing spaces in the series, I feel like option number 1 best fits that by just nipping it in the bud on import.

Ultimately, though, I think any of those three solutions would work just fine. I'm concerned way less about the data itself, and more with the confusion caused by clicking a series filter and having nothing show up.

**Comment by maforget** [comment]
It seems logical to be number 1, but it isn't that easy to do. There are no real built-in way for that.

This is just the code that is used to read the `ComicInfo.xml`.
```c#
return XmlUtility.GetSerializer<ComicInfo>().Deserialize(inStream) as ComicInfo;
``` 

Changing that we would need to go through all the books and all the values to trim them all. This would be expensive. And it would be possible that the space was added by a plugin, then you need to do the same for exporting the file. Then maybe there are values that are already like that in someone DB, then I need to do it for the DB also.

It's one thing to prevent the data from doing that, but we can't prevent all the cases. And like I stated, it's just data. If the data is wrong we can't help it.

I just had a though of what a simple solution would be. I could do that would not add possible duplicates and still have it work correctly is to change the smart list used when filtering to a regex instead. When filtering multiple values field it already does that with a list contains that will ignore spaces. So this would not change how smart list work and would prevent duplicates and still match them.

**Comment by maforget** [comment]
As #104 shows, the regex option doesn't exists on number fields. I will just show the options in the search browser to be exactly what they are, so if 1 entry has multiple variations of spaces they will all be shown.
