### ISSUE TITLE
Some of the Filter options not working

### ISSUE THREAD

**Issue by Gothiclass** [maforget/ComicRackCE#104]
After updating today [21/08/2024] the option to filter by volume wasn't working just shows zero books, did a quick check on the other options and found a few others.

- Book Price
- Community Ratings
- Months
- My Ratings
- Volumes
- Years
![FilterByVolume1](https://github.com/user-attachments/assets/9f250c1e-07b0-44fe-a226-25e8e1bd9f6f)
![FilterByVolume2](https://github.com/user-attachments/assets/6f0426aa-1e80-4412-b47a-b26994401f31)
![FilterByWriter](https://github.com/user-attachments/assets/3445b3d6-9f38-46f8-92ee-9d10c2aad051)

**Comment by maforget** [comment]
That is due to the change Io did due to bug #103. Just didn't consider that number fields don't have access to the regex option. I will revert these changes and just fix it another way.

**Comment by maforget** [comment]
**Note:**
In closer inspection, it is not that these values aren't text. They all use the field AsText, but they still use the normal Matcher. So it will show the value for `VolumeAsText`, but create a smart list to filter based on `Volume`, which it isn't a `ComicBookStringMatcher`, so doesn't have the regex option.
