### ISSUE TITLE
Search box on Library Does not return Fileless entires

### ISSUE THREAD

**Issue by mlubak** [maforget/ComicRackCE#105]
When you put a title in the search box on the main Library, results only show actual issues with Files, and not fileless entries. This use to work at one time in an older version. Not sure if this is a bug or I am doing something incorrectly.
Here is an example search result
![image](https://github.com/user-attachments/assets/058801d9-9c91-46c3-b2f6-34e7a224c60e)

This is what is in the library
![image](https://github.com/user-attachments/assets/966bf11d-6337-4843-87b5-78941149777b)

**Comment by maforget** [comment]
Works fine here, Check under Views => Show only Books is not enabled.

**Comment by mlubak** [comment]
Thanks. Tried that still nothing. I must have something else going on. I even tried show only fileless entries, and then put a title in the search box, and nothing was returned. Any other thoughts ?

**Comment by mlubak** [comment]
Figured it out. In the actual search box, I had filename checked. Not sure how I did that.

BTW, thank you for reviving this program. Your work is greatly appreciated.

You can close this as a bug !

**Comment by mlubak** [comment]
All Fixed
