### ISSUE TITLE
Script window size

### ISSUE THREAD

**Issue by Flyingfufu** [maforget/ComicRackCE#116]
First of all, many thanks for this CE version I've just found ! I'm sure this project will be very successfull !!

Not sure if I post this in the right place, so should I be wrong, let me know. 

**Describe the bug**
Installed multiple scripts in CR without any error indication. Unfortunately, for some of them I can not really use them as the pop up window is fix size and too small, streching all the content to something unusable. Bedetheque or Data Manager are doing fine.

Any idea  how to overcome this situation ?

**Exact Steps to Reproduce**
Install scripts such a Library Organizer 2.1.13 and open the config window. Same with Comic Vine

**Screenshots**

Here an exemple with the Library Organizer one :

![image](https://github.com/user-attachments/assets/6cf4a903-ed34-4fac-8f52-4a55c67119cb)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 6c7f5f1

**Comment by maforget** [comment]
This isn't really a bug with the ComicRack program, but with the plugin itself. They need to take into consideration scaling into windows. The best way to fix it is just set ComicRack CE to set the High DPI setting to System (Enchanced) and it should scale these windows correctly. Beside that there is nothing I can do without the plugin themselves fixing it.

More info here: https://github.com/maforget/ComicRackCE/wiki/High-DPI-Settings-Comparaison

**Comment by maforget** [comment]
It's a windows setting, right-click compatibility => change high DPI settings or change your windows scaling to 100%

**Comment by Flyingfufu** [comment]
Thanks. Tried all different setings, even changing the scling to 100%, but no results.

I've opened a ticket on the plugin github. Hope there is a chance for the owner to fix it or guide me trough a potential hint.

Thanks a lot for your support anyway, really appreciated !

**Comment by maforget** [comment]
I can confirm it works. You need to set this setting along with ticking the box. Changing the setting in windows setting => Display => Scale to 100% will work unless you have some weird custom settings or per monitor. 

![Screenshot 2024-09-23 152902](https://github.com/user-attachments/assets/ddbdbfd3-ebdb-41ef-b830-80d0c7cf5f70)
