### ISSUE TITLE
[Feature request]: Comicrack in tablet reading mode

### ISSUE THREAD

**Issue by llevier** [maforget/ComicRackCE#119]
Hello,

Another need, the old tablet reading mode (with 9 areas on the screen dedicated to a specific function), does not work under Windows 10 22H2 at least.

The "sliding mode" works, but it is not really convenient compared to a simple finger touch.

Great if you can restore this again :-)

Thanks

Brgrds

**Comment by maforget** [comment]
I don't know what you mean, the do work. The problem might be related to your other request #118. They might be too small. Beside using Scaling within windows you can change their size inside the ComicRack.ini file.

**Comment by llevier** [comment]
Hello,
Thanks for the answer. However that is no longer applicable.
Since my previous ComicRack version was hardly working, I moved to yours fully :-)
From that moment, no longer comirack.ini :-(

Can you please tell me which parameters to add to your own configuration to define GestureAreaSize ?

Thanks !

**Comment by maforget** [comment]
All the instructions are on the comment in the Reddit thread I linked. 

> Any special settings are in the `ComicRack.ini` file found in the installation directory. Probably the `GestureAreaSize` setting.
> 
> Copy the file in your data folder (`%Appdata%\cYo\ComicRack Community Edition`) so any changes will not be overridden when updating the program and modify it there.

The ComicRack.ini exists in this version also and includes the `GestureAreaSize` parameter, just search for it and remove the semicolon before so the setting is taken into account.
