### ISSUE TITLE
Publisher icons with years no longer work with blank month field

### ISSUE THREAD

**Issue by devinclancy** [maforget/ComicRackCE#122]
**Describe the bug**

I added some publisher icons with years specified. They seem to work properly when the full date field is populated. *Displayed in UI as (1970/10).*  When the month is blank, it will use the generic or most recent publisher icon. *Displayed as (1970).*

**Exact Steps to Reproduce**

1. Add file to Publshers.zip.: DC Comics(1970-1971)#DC(1970-1971).png
1. Open Comicrack CE, select Action Comics.
1. Scroll to 1970. (Issues 391, 393).
2. Note differences
3. Copy same file to old ComicRack.
4. File displays correctly

**Screenshots**

**ComicRack CE:**

![comic rack CE publisher logo](https://github.com/user-attachments/assets/a4683bb2-9788-4ab7-be0a-c8793d6c0519)

**Old ComicRack:**

![comic rack original publisher logo](https://github.com/user-attachments/assets/cf40fc4f-c735-4a58-9756-be2aa2636178)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 9c4ae21

**Comment by devinclancy** [comment]
[Uploading Publishers.zip…]()

**Comment by maforget** [comment]
Related to changes done in #111.

**Comment by maforget** [comment]
> Uploading Publishers.zip…

Please reupload it didn't work

**Comment by devinclancy** [comment]
[Publishers.zip](https://github.com/user-attachments/files/17531614/Publishers.zip)

Trying again.

**Comment by maforget** [comment]
I've also added your DC Comics icons in the last build.  b6392f32666f16c53a36f6649c2d6fa0ef25c351
