### ISSUE TITLE
Support of international characters (French accent) in the folder view - 

### ISSUE THREAD

**Issue by greatcoco** [maforget/ComicRackCE#123]
**Describe the bug**
Accented and accent characters from non English language is displayed correctly but the alphabetical sort is not working correctly

File explorer 
<img width="357" alt="image" src="https://github.com/user-attachments/assets/2b7beea4-a755-46aa-9863-08042084b7de">

Comic rack view 
![image](https://github.com/user-attachments/assets/7243dc15-779b-4bb7-89dd-4caae0c5e4f6)

**Exact Steps to Reproduce**
1. Go to folder view within a folder with a mix of English characters and folder names with accent

**Screenshots**

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 03be52c

**Additional context**
Not a bug but just difficult to find a folder / file as the sort is not sorting correctly. It also depends on the position of the accent characters in the filename, if it's at second position, it's easy it will be at the bottom of the list, but if it's in the middle , it may be after the letter

**Comment by maforget** [comment]
Fixed in the next build

**Comment by greatcoco** [comment]
Works perfectly , thanks for the quick fix !

**Comment by greatcoco** [comment]
The latest build seems to have reverted the old behavior  (to quote yourself :sorted folders in folder view using  invariantCulture )

**Comment by maforget** [comment]
There as been no change in that regard, Still the same behavior.

![Image](https://github.com/user-attachments/assets/873a7e2c-a880-4c55-b834-708e89956eb1)

**Comment by greatcoco** [comment]
With version 5a3cc15 ; its working 

![Image](https://github.com/user-attachments/assets/5d22e62e-f874-47b3-be58-c47e91e956f8)

With version 

![Image](https://github.com/user-attachments/assets/2141a916-7145-4027-a7d4-22d22dde095d)

It stopped working,  but I just reinstalled and now I got version 7f35Aaa , weird, must be an issue between the chair and the keyboard :) sorry for false positive

**Comment by maforget** [comment]
Version 8295041 is from July 9th 2024, before the change on Oct 29th. You were using an old version that is why.

**Comment by greatcoco** [comment]
Ok a plausible answer, automatic upgrade downloaded a new version, the browser detected an old version and appended (3) to the downloaded file, is it possible that the script will run the version without (3) and install then an older version, bottom line, I need to make sure that I clean / remove old version before upgrading if it's confirmed to be the behavior. Thanks again for this great community edition.

**Comment by maforget** [comment]
Possible the program only opens the browser so everything else after that is out of my hands. Since that was an old version without update checking it didn't alert you of a new version.
