### ISSUE TITLE
seeding comics and sharing them on DC++

### ISSUE THREAD

**Issue by pingu6** [maforget/ComicRackCE#30]
as you know you can't edit files that you are seeding and if you share edited files on DC++ you will get banned, so does ComicRackCE edit the/add `ComicInfo.xml` file?

as far as i know [kavita](https://wiki.kavitareader.com/en/guides/get-started-using-your-library/adding-and-editing-metadata#metadata)/[komf](https://github.com/Snd-R/komf?tab=readme-ov-file#important) does have two options store the metadata in a database or `ComicInfo.xml` file, it will be nice if ComicRackCE does have that too

**Comment by Totengeist** [comment]
Both the original ComicRack and CE have this. I think you just need to go to Edit &rarr; Preferences &rarr; Advanced and make.sure "*Allow writing of Book info into files*."

**Comment by pingu6** [comment]
> Both the original ComicRack and CE have this. I think you just need to go to _Edit_ → _Preferences_ → _Advanced_ and make sure "_Allow writing of Book info into files_."

i searched the settings and i didn't see that, thanks

**Comment by maforget** [comment]
Check the [wiki page](https://github.com/maforget/ComicRackCE/wiki/Writing-the-metadata-inside-the-Comic-book-file) about it.
