### ISSUE TITLE
Problems with metadata copy and CTRL+C and CTRL+V

### ISSUE THREAD

**Issue by saskir12** [maforget/ComicRackCE#32]
Don't know if it is my Surface but strangely I can not copy the metadata with the keyboard combination. Only with right click and the commands there. Thought at first it was because the cursor was not above the cbz but this was not the case.

Can anyone test if they have the same problem? It did work for me for the version 1-1.5 weeks ago.

**Comment by saskir12** [comment]
Oh this should not be a problem as this is just how it is written here. English Keyboards call it "Control" and German ones "Steuerung". Internally those are the same ones. It just tells the computer it should do an action which is linked to a key combination so it knows CTRL+C stands for copy. The bits it sends are the same.

**Comment by saskir12** [comment]
Hmmm, then it seems it is my Surface.

**Comment by maforget** [comment]
Does Ctrl+C work with copying lists? What about Ctrl+C to copy the page when reading a book or from the Pages tab? Do other shortcut keys work also like Ctrl+G. 

Do you have any software that could be interfering. I had similar problems with Nvidia Geforce Experience, that prevented some shortcut to work.

**Comment by saskir12** [comment]
So did test it (sorry for the long wait, hectic job atm). Other Shortcut works, only this seems to not work. Although I think I found the culprit. Seems that if I deactivate MS Powertoys it works. But strangely on another PC (tried it on a Steam Deck with windows 11), it works normally even with powertoys installed. So most likely my Surface has a problem.
