### ISSUE TITLE
Portable not working

### ISSUE THREAD

**Issue by francescobaiocchi** [maforget/ComicRackCE#34]
Cannot have a portable installation working. 
If you uncomment "UseLocalSettings = true" row in file "ComicRack.ini" result is application not anymore starting.

**Comment by maforget** [comment]
I've been using it. Removing the line also wouldn't prevent the program from starting. It just would just open the program normally. 

More information is needed. Exact steps to reproduce, are you using any command line switches? Where is the ComicRack.ini located? Any other ones in other folders like Data/ProgramData? Where is your portable install located? Does your user have write permissions to that folder?

Are you certain that the application isn't still open in the system tray so you think it isn't opening? Which version are you using (check the about, there is the commit version between brackets).

**Comment by francescobaiocchi** [comment]
Sorry, my fault.
It was a trivial problem concerning write permissions in the folder.
That's because I was using the default folder under "C:\Program Files".
Thank you, I'm closing the issue.
