### ISSUE TITLE
Selecting a Folder that doesn't exist anymore shows ComicRack's own folders instead. 

### ISSUE THREAD

**Issue by shanezuspan** [maforget/ComicRackCE#36]
**Describe the bug**
Ran library organizer on an files in an unprocessed folder. Files renamed and moved. Went back to "empty" folder and found new list of random files. 

**Screenshots**
![2024-02-16_05-14-54](https://github.com/maforget/ComicRackCE/assets/55251478/be9197f0-170c-4c4b-9e95-470369aa419d)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - V 0.9.180 [801adcb] 64bit

**Comment by maforget** [comment]
Refresh the folder. I've seen that happen when a folder doesn't exist anymore it shows the files from ComicRack folder. These aren't created just shows it's own file.
