### ISSUE TITLE
Maincharacterorteam and Review aren't exported to comicinfo.xml

### ISSUE THREAD

**Issue by SenorSmartyPants** [maforget/ComicRackCE#41]
**Describe the bug**
These fields are saved to the database but not exported into comicinfo.xml

**Exact Steps to Reproduce**

**Screenshots**

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: e4fca3f

**Additional context**

**Comment by maforget** [comment]
I can't believe no one discovered that since just now. The OG had the same problem it seems (based on the code). To be clear it did export correctly when using the Export, but the problem was when using the Update File (or copy to clipboard).

**Comment by SenorSmartyPants** [comment]
I mentioned it somewhere years ago. Glad it's fixed now. I'll have to update to CRCE!
