### ISSUE TITLE
Comic Vine Scraper window is too small and cannot be resized

### ISSUE THREAD

**Issue by mark-4dollar** [maforget/ComicRackCE#42]
**Describe the bug**
Comic Vine Scraper window is too small and cannot be resized

**Exact Steps to Reproduce**
Select a book from your library.
Right Click --> Info OR press CTRL i
Click Comic Vine Scraper from the bottom bar
Notice the window is too small and cannot be resized.  Right clicking the title bar has the option to maximize but it is disabled as well.

**Screenshots**
![Capture](https://github.com/maforget/ComicRackCE/assets/2414133/9c274552-cbf1-4ee4-a84e-99cc4b3e0c42)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 58dd860

**Additional context**
Comic Vine Scraper Script
- Version: 1.0.101
- Commit 725fe2d

**Comment by saskir12** [comment]
Oh this happened also in the normal CR version. This has something to do with how Windows handles the magnifying options as the field you mentioned always stay the same size no matter how big the fonts get changed. Atleast from my observations. Strangely I had once a bug where the whole CR had the right magnifying size and all was correct as it should be. But after a restart it reverted back.

**Comment by maforget** [comment]
Not really something I can do about it. You should post it on the ComicVine scrapper GitHub instead. This isn't a ComicRack bug.

**Comment by mkschultz-sunrun** [comment]
Understood.  Thank you, @maforget for the reply.
