### ISSUE TITLE
"Show in List" Redirects Incorrectly

### ISSUE THREAD

**Issue by carfa34** [maforget/ComicRackCE#43]
**Describe the bug**
When using "Show in List" on any comic file, it redirects to whatever the last "List" option is regardless of what is chosen.

**Exact Steps to Reproduce**
1. Right click any comic file.
2. Click on 'Show in List'
3. Click any List option.
4. Be redirected to whatever last List option is.

**Screenshots**
Attached short video clip. Can provide more if needed.

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 44d1d2

**Additional context**
Not a big issue, just an inconvenience. The bug is there on current latest build "44d1d2" and whatever was the most recent one. Can't remember if it was there on earlier builds.

https://github.com/maforget/ComicRackCE/assets/151964748/884bd53f-98dd-43bd-8f4b-0ab7b7317e98

**Comment by maforget** [comment]
Ok that was weird, never touched that part. It was because of the decompilation the variable was declared before the loop instead of inside. It's been a while since I decompiled this, newer program show it properly.
