### ISSUE TITLE
Need an Installer for Release

### ISSUE THREAD

**Issue by maforget** [maforget/ComicRackCE#5]
Attached is a decompiled copy of the existing installer script. Would need an installer for actual release and be integrated in the Github workflow.

[[NSIS].nsi.txt](https://github.com/maforget/ComicRackCE/files/13961061/NSIS.nsi.txt)

**Comment by Totengeist** [comment]
Have you done any investigation into installer packagers or have a preference? I have some experience with Inno Setup, but can look into getting NSIS going since we have the existing script.

**Comment by maforget** [comment]
Not at all, I know I put high priority, because it should be done for a release. But I don't know when that would be and current zip is fine with me. I know it's hard for some users and we would need to have association with file types and crplugin files to be done.

You are free to do it, if you can. I am guessing it will be a step in the github workflow or maybe a configuration like ReleaseInstaller.

**Comment by Totengeist** [comment]
I'm slowly working my way through creating an installer with NSIS. There are a lot of errors for missing DLLs. It seems to be looking for the DLLs that are in the `Resources` directory, but expecting them in the main directory. It'll take me a bit to get my head around the current project structure and how to let NSIS know where everything is. Hopefully, I'll have the existing script working in a couple of days.

**Comment by Totengeist** [comment]
Once I got the location of all the files figured out, it actually wasn't that bad. There are still some issues, but it's enough for a draft PR. I'll probably submit that tonight with notes on the current state and a couple of detail questions. As I expected, Defender immediately quarantined the installer when I tried to run in as per #16.

**Comment by saskir12** [comment]
Maybe a strange workaround (and I assume it goes against github policy) but how about making a batch which installs the OG CR and then replaces the installed files with the new ones? So even those not tech savvy (ok, you don't need to be a genius for this) can install it easily. But as said I assume Github will not allow an installer made from someone else. Or rather in this case a batch file with an installer.

**Comment by maforget** [comment]
> Maybe a strange workaround (and I assume it goes against github policy) but how about making a batch which installs the OG CR and then replaces the installed files with the new ones? So even those not tech savvy (ok, you don't need to be a genius for this) can install it easily. But as said I assume Github will not allow an installer made from someone else. Or rather in this case a batch file with an installer.

But why? To prevent flagging by the AV? It would still flag the new files. And it wouldn't make thing easier.

**Comment by Totengeist** [comment]
I'm not sure what I did, but I accidentally submitted two PRs. I've closed one of them now. Sorry for any inconvenience.

**Comment by saskir12** [comment]
OH, not for the flagging. For someone who is uncomfortable in putting it in a folder, making a manual entry for opening the CR files with it, etc. Was meant as a workaround for those who want a exe to install it.

**Comment by Totengeist** [comment]
> For someone who is uncomfortable in putting it in a folder, making a manual entry for opening the CR files with it, etc. 

I should have a proper installer setup in the next 24 hours. It might take some feedback and tweaking, but should be sufficient for most people.

**Comment by saskir12** [comment]
Nice to know. Thanks to you both for your work. Will test it when it is ready. But as a question. I noticed with the old isntaller that it says it "optimizes Windows settings". If you looked into the old installer. What was meant with this? File associatiion, enviroment variables? Or something deeper?

**Comment by maforget** [comment]
Read again, it doesn't say optimize windows settings, it says optimize ComicRack. It's a bit technical, but program done with the .NET Framework aren't compiled to machine language, but to an Intermediate Language (IL) and the .NET Framework Runtime converts it on the fly to machine language, it's called Just in Time compilation. Java is also such a language. The benefit is that a lot of things like memory management is handled by the framework (as opposed to by the programmer for programs in like C++). It removes a lot of the very complicated details. Since we are using JIT we can have the same binary work on a 64bit or 32bit client, or maybe an ARM client. A lot of the optimization is done on the fly by the framework for your computer. This IL is why we are able to decompile and recreate the code to be almost like the original.

Problem is that this creates some overhead, that's why you will hear that high performance applications like games are created with C++, but that is a lot harder to have to deal with things like garbage collection of the memory yourself.

The Optimize option of the installer will run a tool called NGEN, that will pre-compile the binary to machine language directly at the install time. It is supposed to help with memory usage and faster start up (since the framework doesn't need to run). But it also comes with some draw backs, first you need to have administrator access, so if you don't have that then you can't use that function or if you are using it in portable mode. Also with the ever changing program with a lot of updates, we could be in a situation where the program loads the older pre-compiled version instead of the new updated one. If you ever used my Support Pack, I had to change the binary to bypass that, because the new changes wouldn't be taken into consideration. You also have the problem that with all the dependencies (other libraries, the dlls) that ComicRack depends on, the moment only one isn't optimized, the framework needs to load anyway, so we lose the benefits. You also lose the benefits of having the Framework adapt on the fly to your situation.

I don't believe that Memory is has much a problem as it was back then. And it won't improve startup time dramatically either. It will just introduces further potential problems. And if we do switch to the newer .NET versions, we will have the ability to create Ahead-of-TIme compilation then anyway at that point.

**Comment by saskir12** [comment]
Ah thanks for the clarification.
