### ISSUE TITLE
What version of MariaDB is supported

### ISSUE THREAD

**Issue by killo3967** [maforget/ComicRackCE#51]
I see in the log:
 "CHANGE: Switched MySQl library to MySQLConnector for better speed & compatibility with MariaDB" 

This mean i could use the last version of MariaDB?

**Comment by maforget** [comment]
Yes, tested with version 10 & 11. Just a short test though, opens, add a book, book shows in DB. 

Some one commented coming from v5 and had problems with character encoding. So make sure to use the default of utf8mb4. 

Make a backup just in case if upgrading from an ancient version.
