### ISSUE TITLE
Better Software filtering

### ISSUE THREAD

**Issue by Nivyan** [maforget/ComicRackCE#56]
https://github.com/maforget/ComicRackCE/assets/5938853/7788d7cd-34b9-4f1a-ab6e-745245852665
(view in full-screen to see the issue more clearly)

I've noticed an issue where a gray vertical line appears between two pages when they are displayed together. This line, while not a problem for most comics, disrupts the flow of artwork in two-page spreads. In the original comics, these spreads are seamless, but the gray line creates an artificial and distracting division. I've attached a video to demonstrate how this affects the reading experience, especially in digital formats where such separation is not present, unlike the physical versions. It would be great to have an option to disable this line for a more immersive reading experience.

**Comment by maforget** [comment]
Have you played with the filters? This is probably related to the filters and OpenGL #23. I don't think it's there for any reason. 

Try changing hardware/software filters, Enabling/Disabling Hardware Acceleration. The fact that it appears after the fact is related to that I am pretty certain. If you could pinpoint which it would help.

**Comment by Nivyan** [comment]
> Have you played with the filters? This is probably related to the filters and OpenGL #23. I don't think it's there for any reason on purpose.
> 
> Try changing hardware/software filters, Enabling/Disabling Hardware Acceleration. The fact that it appears after the fact is related to that I am pretty certain. If you could pinpoint which it would help.

Thank you for the quick response!

I found out the line disappeared with these specific settings, none of the other combinations made the line disappear. I didn't check things at thoroughly as I thought. Sorry for opening a ticket on a non-issue.
![image](https://github.com/maforget/ComicRackCE/assets/5938853/a566731c-bda4-48db-af54-a3eb78d7ba29)

**Comment by maforget** [comment]
Seem related to this part of the code, so yes only does that with Hardware & Software filters.

https://github.com/maforget/ComicRackCE/blob/4856eec3f79abc74907475a6e3cb6df89e22bbe7/ComicRack.Engine.Display.Forms/ComicDisplayControl.cs#L1598

**Comment by maforget** [comment]
Maybe try this build #83 (a download link is in a comment). 

The Software filtering just uses Windows default GDI, this build uses another library, maybe it is better?

**Comment by Nivyan** [comment]
> Maybe try this build #83 (a download link is in a comment).
> 
> The Software filtering just uses Windows default GDI, this build uses another library, maybe it is better?

I've "solved" the issue, but I'm sorry to say I don't know what caused it. I kind of gave up and I only noticed right now that it stopped showing up.
