### ISSUE TITLE
Open in external comic viewer

### ISSUE THREAD

**Issue by Hexaphim** [maforget/ComicRackCE#61]
I'm not a huge fan of the CR comic viewer. Would it be possible to add an option to open a comic in an external viewer?

**Comment by maforget** [comment]
In the meantime there is the Open With plugin you can use.

**Comment by Hexaphim** [comment]
I tried Open With 1.5, but it doesn't seem to work - I don't get an Open with... option when I right-click.

**Comment by maforget** [comment]
You need to build the menu with the entries you want. Go to File=>Automation and use the Build Open With Menu. Choose your file type and location of exe and it will create an entry in the right click menu for that program when you restart.

**Comment by Hexaphim** [comment]
Thank you, I forgot to mention that this worked. I was looking at the right-click automation menu, not in File.

**Comment by Hexaphim** [comment]
Great implementation, thanks a lot!
