### ISSUE TITLE
Logo publishers with special charaters in name not show.

### ISSUE THREAD

**Issue by killo3967** [maforget/ComicRackCE#63]
Publisher logo images that have names with accents, accents, and umlauts are not displayed.

In my case i updated the publisher.zip with the logos of:

Éditions Glénat
Les Humanoïdes Associés
Denoël Graphic

But not logos show in Tiles-view.
Tested also in old comicrack and works fine.

**Comment by maforget** [comment]
Let's all keep discussion on the Publisher.zip on the previous issue #62.
