### ISSUE TITLE
Page Turn Effect doesn't take into account right-to-left reading mode

### ISSUE THREAD

**Issue by QueenNiamh** [maforget/ComicRackCE#64]
**Describe the bug**

When using right-to-left reading mode with Page Turn Effect enabled, the page turning animation still behaves as if I'm reading a left-to-right book instead of being flipped to match the reading direction as one would expect; this is very disorienting and affects readability for manga and other right-to-left comics.

**Exact Steps to Reproduce**
1. Enable Page Turn Effect under Book Display Settings
2. Open a book meant to be read right-to-left
3. Enable Right-to-Left Reading
4. Turn the page of the book

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: cb76e9b

**Comment by maforget** [comment]
To add to that there was talk about switching the back & forward button.

**Comment by maforget** [comment]
I will close that has invalid, because you can do it already. You need to enable the `True right to left reading` in Preferences.
