### ISSUE TITLE
Fullscreen also toggles Minimal User Interface doesn't work when using Reader in own Window

### ISSUE THREAD

**Issue by DorkN313** [maforget/ComicRackCE#70]
Fullscreen toggles Minimal User Interface doesn't work when using Reader in own Window.

**Exact Steps to Reproduce**
1. Turn on Reader in own Window (F12)
2. Go to Preferences - Behavior - Reading and turn on Fullscreen also toggles Minimal User Interface 
3. Go fullscreen (F11)
4. Minimal User Interface doesn't turn on

 - Version: 0.9.180
 - Commit: e4fca3f

**Comment by maforget** [comment]
I've fix this, but it was specifically mentioned that it wouldn't work with reader in it's own window. I haven't checked more if it creates other problem, so please keep an eye open.

P.S. Also your version is very old, you can check changes with the old News option.
