### ISSUE TITLE
Windows Defender detects Trojan:Win32/Bearfoos.A!ml in latest nightly

### ISSUE THREAD

**Issue by scinos** [maforget/ComicRackCE#71]
**Describe the bug**

Windows Defender detects Trojan:Win32/Bearfoos.A!ml in latest nightly

**Exact Steps to Reproduce**

Install the latest nightly from commit  5e743cd. Wait for the error

**Screenshots**

![image](https://github.com/maforget/ComicRackCE/assets/975703/beda8135-99be-4201-a475-189171a41837)

**Version/Commit (check the about page, next to the version, for the string between brackets):**
 - Version: 0.9.180
 - Commit: 5e743cd

**Comment by maforget** [comment]
I don't have any detection, and not in VIrusTotal also.

**Comment by scinos** [comment]
I think I only saw it after I exported a comic to CBZ? Not sure to be honest.
