### ISSUE TITLE
Consolidate listing when writer, penciler, inker, etc. are the same

### ISSUE THREAD

**Issue by chowbok** [maforget/ComicRackCE#75]
It's a little silly how credits are listed:

![Screenshot_2024-05-14_22-40-40](https://github.com/maforget/ComicRackCE/assets/20290033/2d9fec05-94d2-4fd3-b0aa-fc0090e8ccf8)

Can logic be added so that it only lists a name once if he/she has multiple roles on a comic?

**Comment by chowbok** [comment]
Sorry, I didn't mean to label this "bug", but I don't see how to change that.

**Comment by maforget** [comment]
Done.

**Comment by chowbok** [comment]
Thanks very much!
