### ISSUE TITLE
#enhancement Add Main Series Format icon

### ISSUE THREAD

**Issue by JFinnTeacher** [maforget/ComicRackCE#77]
Hopefully this will be straightforward.

In Format.zip rename series.png to series#Main Series.png to have it show up as Icon for Main Series Format. This is the only format without an icon.

**Comment by maforget** [comment]
This should all be done in issue #62. 

But shouldn't we have a different icon for Main Series? 

Main Series is also not a a default format, so unless you use it it will not appear anywhere. I am all to add it as a default, but maybe it could have a custom icon instead? Maybe @ucapato that provided the updated formats on the other issue, could help with creating one for Main Series?

**Comment by ucapato** [comment]
Hi,

I am sorry, I just saw it now. I can work on a "Main Series" Icon. Could it be MSE, or MSS...? Any suggestion is welcome.

**Comment by maforget** [comment]
I don't know if @JFinnTeacher that suggested that has an idea? 

Are we are stuck with max 3 letter words? I feel any of these (MSE, MSS) are confusing. The best would be "Main" if it can be fitted in a square logo and following the same style, or just a big M.

**Comment by ucapato** [comment]
I am ok with "Main", no problem at all. I am learning how to work with some nice tools and maybe I could create an entire set of new icons for the Format.zip. 
Let me work in some samples and bring it here to you. If you guys approve this "new look" we can go to this direction.

**Comment by ucapato** [comment]
All right,

I got it now! 
I would like to present a proposal with a more renewed view from the Series Format package (Format.zip). 
Feel free and honest to comment. I will still work only on the regular "MAIN.png" format icon as discussed here. But I thought it could be interesting to take a look into this package.

For obvious reasons o used the same naming as from the original and added a few more for testing purposes only. They are:

Black & White#B&W#B_W (option 1).png  ==> A renewed view from the original B/W format
Black & White#B&W#B_W (option 2).png ==> An optional view as "B&W"
Main#Main Series.png ==> The new suggested/missing format file
Year One#Year 1 (option 1).png ==> A renewed view from the original Y1 format
Year One#Year 1 (option 2).png ==> An optional view for "YearOne"
Year Zero#Year 0 (option 1).png ==> A renewed view from the original Y0 format
Year Zero#Year 0 (option 2).png ==> An optional view for "YearzZero"

After a quick test I believe the optionals for Y1 and Y0 did not look nice (of course, it is too small for 64x52 icon format). But maybe the rest might be interesting to take a look at.

I took a snapshot from my CRCE as an example and I am attaching the complete zip with all the above.

<img width="1411" alt="image" src="https://github.com/maforget/ComicRackCE/assets/125318439/3e241ef4-cb0e-4b5d-823f-c4859581bbb2">
[Formats.zip](https://github.com/user-attachments/files/16021806/Formats.zip)

**Comment by maforget** [comment]
I like how the pop more, are more legible. 

- The Main icon is perfect. 
- I prefer the B&W (option 2)
- Your Year One & Year Zero are inverted. My suggestion might be a mix of option 1 & 2. keep the option 1, but make the number smaller like the text in option 2.

I've posted the link to this thread on Discord asking for feedback.

Great work

**Comment by ucapato** [comment]
Great,

Thanks for the quick feedback. Changes made:

Removed Black and White Option 1 (I also prefer option 2 )
Fixed Year 1 and Year 0 by just keeping Option 1 and making numbers a little smaller.

[Formats.zip](https://github.com/user-attachments/files/16025095/Formats.zip)

**Comment by azuravian** [comment]
These look fantastic.  Ipropose that the crossover icon be changed to something like the shuffle icon in music players.  If you Google crossover icon, this is what comes up.  I feel it would match better than the circular arrows.

![image](https://github.com/maforget/ComicRackCE/assets/7379812/0c1daf5b-42c6-4800-a1d4-edd128ef20f7)

**Comment by ucapato** [comment]
Great,

@azuravian thanks for the feedback and proposal. 

So, for Crossover.png, we went from this:
![Crossover](https://github.com/maforget/ComicRackCE/assets/125318439/e9c04cc0-a6c8-48e7-a36a-80ae3c8b48f2)

To this:
![Crossover](https://github.com/maforget/ComicRackCE/assets/125318439/6ba0bd21-94b8-44e4-b2a9-5769cfea40d0)


I took to chance to improve a bit NSFW.png (I didn't like the first version I did).
from this:
![NSFW](https://github.com/maforget/ComicRackCE/assets/125318439/41b2b1bc-8bf1-4295-9024-481b87880125)

To this:
![NSFW](https://github.com/maforget/ComicRackCE/assets/125318439/aac1f265-7ae9-4bbe-aed3-723074ef7478)


Here comes the latest update with all changes discussed so far.

[Formats.zip](https://github.com/user-attachments/files/16026840/Formats.zip)

**Comment by azuravian** [comment]
New crossover is fantastic.

**Comment by maforget** [comment]
Just a FYI on how icons are now stored on github, see [this comment](https://github.com/maforget/ComicRackCE/issues/62#issuecomment-2201705532) on the other issue.

**Comment by maforget** [comment]
@ucapato Something that seems to be missing from the Format icons upgrade are the ones that are in Specials (there are 4). They contains some pretty important things like 100% Complete & Manga.

Is it possible to also upgrade these, because they are still in the old "Yellow" style. 

Maybe `BlackAndWhite` can remain in white, but `Manga`, `MangaRightToLeft` & `SeriesComplete` would need to be updated also. They are appear pretty regularly.

**Comment by ucapato** [comment]
> @ucapato Something that seems to be missing from the Format icons upgrade are the ones that are in Specials (there are 4). They contains some pretty important things like 100% Complete & Manga.
> 
> Is it possible to also upgrade these, because they are still in the old "Yellow" style.
> 
> Maybe `BlackAndWhite` can remain in white, but `Manga`, `MangaRightToLeft` & `SeriesComplete` would need to be updated also. They appear pretty regularly.

No problem. I'll work on those :-)

**Comment by ucapato** [comment]
Hello,

Here are my suggestions:

**From right to left** (tried to keep it quite simple and to the standard from the previous ones)

from 
![MangaRightToLeft](https://github.com/user-attachments/assets/654517e7-0cbf-4bc4-a481-e6784969a26b)

to
![MangaRightToLeft](https://github.com/user-attachments/assets/6969201d-5e29-4e04-a7f4-7e0155e44f84)


**Black and White** (Tried with some different fonts)

from 
![BlackAndWhite](https://github.com/user-attachments/assets/91f4da28-c3b5-4002-b13a-d79c9223182b)

to
(1)
![BlackAndWhite(1)](https://github.com/user-attachments/assets/c70654af-3d80-4797-8eae-b5bce6738c55)
(2)
![BlackAndWhite(2)](https://github.com/user-attachments/assets/a8c9ced5-8565-4a36-85c8-50be3a2e4ea2)
(3)
![BlackAndWhite(3)](https://github.com/user-attachments/assets/1df96226-0c86-4b00-b8e7-d68256a30ab3)
(4)
![BlackAndWhite(4)](https://github.com/user-attachments/assets/ab479269-b0e7-4bb4-bb22-297010a910df)
(5)
![BlackAndWhite(5)](https://github.com/user-attachments/assets/5ca4b49a-c040-48e4-940b-0b85754dc7cc)
(6)
![BlackAndWhite(6)](https://github.com/user-attachments/assets/a4de9aa2-6599-471d-814c-cd135ffad90c)


**Manga** (also tricky, I was looking for more "handwriting" kanji. I vote for (1) for sure)

from
![Manga](https://github.com/user-attachments/assets/ffcc3173-90a1-4a91-a7f9-1e99b19de577)

to
(1)
![Manga(1)](https://github.com/user-attachments/assets/27609568-a8fa-47ee-ab93-dbf8eb0ef999)
(2)
![Manga(2)](https://github.com/user-attachments/assets/0d416a11-6bac-4d72-9690-fa463015956e)
(3)
![Manga(3)](https://github.com/user-attachments/assets/a0eccdb0-03c5-4e46-a433-173556864ba7)
(4)
![Manga(4)](https://github.com/user-attachments/assets/d8b0a3e9-da22-41c7-a067-b95a49054fa7)


**100%** (The complete series icon. I've tried the regular standard, and brought a more "comic book" option as well)

from
![SeriesComplete](https://github.com/user-attachments/assets/721c5511-58ec-47f3-8ee5-15cb795a8be3)

to
(1)
![Asset 183SeriesComplete](https://github.com/user-attachments/assets/72567202-6c93-49cb-878a-e8a0a6fa701b)
(2)
![Asset 184SeriesComplete](https://github.com/user-attachments/assets/089de7fa-104b-4dca-9398-64eb446623a1)

**Comment by ucapato** [comment]
Here a an example of how it should look like:

<img width="398" alt="image" src="https://github.com/user-attachments/assets/7ae95040-1e8e-4e93-aabc-e333af4548f2">


I think the "Manga.png" maybe needs to be with the stroke thicker:
![image](https://github.com/user-attachments/assets/5cecb5b8-5414-4f6d-9629-982238211448)

**Comment by ucapato** [comment]
ok, I guess I got it now. 
So please, consider the Manga options from above with a final touch as this one below:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/0f8ac1cd-eb35-4aa5-b91c-f788e73d70a3">

**Comment by maforget** [comment]
These are great, I agree that i prefer the 1st for Manga, for B&W the first seems fine but whatever font matches the other ones. I like the RightToLeft reading it's a lot clearer what it means. 

For the 100% complete it looks great, but the 2nd icon seems to resemble others I have seen way too much. I can't seem to not see a resemblance with the getcomics logo.

**Comment by ucapato** [comment]
Yes, you are right. The CompleteSeries resembles Getcomics (I knew those colors looked familiar somehow).
I attempted to use Comic Rack Icon colors instead. 

![SeriesComplete(2)](https://github.com/user-attachments/assets/9cd1fcd9-3b26-47a0-a1cb-cc4a11286b9c)

**Comment by ucapato** [comment]
Here we go:

<img width="70" alt="SeriesComplete(3)" src="https://github.com/user-attachments/assets/ae25b036-aa1e-4891-bafd-34c043fed800">

I changed the thin crossing stripe color into "100%" from white to a more "orange shade like". I believe this makes the 100% more readable.

I tried on my CRCE and pulled the Info Panel for a better visualization:

![image](https://github.com/user-attachments/assets/1ec33bab-07a3-4092-b4a7-db504f0c17a1)

If those are ok, I'll create PR with them. Any other suggestions are pretty much welcome.

**Comment by maforget** [comment]
This looks nice, but I can still see some glare in that line, maybe it needs a bit of a gradient towards the end, as to not remove it completely.

**Comment by ucapato** [comment]
Sure, no problem.

Maybe something like this?

<img width="75" alt="SeriesComplete(5)" src="https://github.com/user-attachments/assets/a06cdd34-586b-4b89-8fb0-5a81684bdf86">


From the Info Panel:

![image](https://github.com/user-attachments/assets/f5a7b152-8d27-4ec7-91b0-c09c79e3ab16)

**Comment by ucapato** [comment]
or even by flipping the gradient from the ballon:

<img width="76" alt="SeriesComplete(6)" src="https://github.com/user-attachments/assets/1fbcc588-8881-42d0-93e5-f17c6801e924">


![image](https://github.com/user-attachments/assets/e96a303d-6e5b-4244-8219-96e8e055b2ce)
