### ISSUE TITLE
Library Organizer: Greyed Out Options for "Custom"

### ISSUE THREAD

**Issue by PfantomKATT** [maforget/ComicRackCE#80]
When opening the Library Organizer (v2.1.13), on both the "Files" and "Folders" options, the "Custom" selection at the bottom is greyed out. I checked the preferences to make sure that "Show Custom Book Fields" in the "Behavior" section is checked as enabled.
![Library Organizer - Files View](https://github.com/maforget/ComicRackCE/assets/165111850/4fd6a473-9d0b-4868-8479-41399b9f963c)
![Library Organizer - Folders View](https://github.com/maforget/ComicRackCE/assets/165111850/ba35ac7f-bf4f-4e31-8ca4-320cfc35a8af)
![Preferences](https://github.com/maforget/ComicRackCE/assets/165111850/4e21f69a-66ef-4a7a-bbe8-3f7a25048803)

**Comment by maforget** [comment]
Library Organizer isn't related to ComicRackCE, beyond the fact that it's a plugin for it. I am not the maintainer of said plugin. I see no reason why ComicRack itself would be the culprit. 

You are better served by posting in the Library Organizer GitHub or ask on Reddit if anyone knows the reason.
